"""
chat/actions_config.py — Predefined actions registry mapping for realBOT M2.8.
Includes Internal Navigation, Communication, Location/Maps, Social,
Government Services, and Business Actions.
"""

DEFAULT_ACTIONS = [
    # ── 1. Internal Navigation ────────────────────────────────────────────────
    {
        'action_name': 'nav_home',
        'category': 'Internal',
        'action_type': 'internal_nav',
        'display_name': 'Home',
        'description': 'Navigate to the Propertism Homepage',
        'target_url': '/',
        'supported_parameters': [],
        'confirmation_required': False,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'nav_about_us',
        'category': 'Internal',
        'action_type': 'internal_nav',
        'display_name': 'About Us',
        'description': 'Learn more about Propertism',
        'target_url': '/about/',
        'supported_parameters': [],
        'confirmation_required': False,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'nav_services',
        'category': 'Internal',
        'action_type': 'internal_nav',
        'display_name': 'Services',
        'description': 'View our property management service offerings',
        'target_url': '/services/',
        'supported_parameters': [],
        'confirmation_required': False,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'nav_listings',
        'category': 'Internal',
        'action_type': 'internal_nav',
        'display_name': 'Property Listings',
        'description': 'Browse premium listings in Chennai',
        'target_url': '/properties/',
        'supported_parameters': [],
        'confirmation_required': False,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'nav_property_details',
        'category': 'Internal',
        'action_type': 'internal_nav',
        'display_name': 'Property Details',
        'description': 'View specific property listing details',
        'target_url': '/properties/{property_id}/',
        'supported_parameters': ['property_id'],
        'confirmation_required': False,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'nav_resource_hub',
        'category': 'Internal',
        'action_type': 'internal_nav',
        'display_name': 'Resource Hub',
        'description': 'Official Tamil Nadu and NRI property services directory',
        'target_url': '/property-owner-resources/',
        'supported_parameters': [],
        'confirmation_required': False,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'nav_faq',
        'category': 'Internal',
        'action_type': 'internal_nav',
        'display_name': 'FAQ',
        'description': 'Frequently Asked Questions about NRI property management',
        'target_url': '/faq/',
        'supported_parameters': [],
        'confirmation_required': False,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'nav_contact',
        'category': 'Internal',
        'action_type': 'internal_nav',
        'display_name': 'Contact',
        'description': 'Get in touch with our office support team',
        'target_url': '/contact/',
        'supported_parameters': [],
        'confirmation_required': False,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'nav_terms',
        'category': 'Internal',
        'action_type': 'internal_nav',
        'display_name': 'Terms & Conditions',
        'description': 'Read our platform Terms & Conditions',
        'target_url': '/terms/',
        'supported_parameters': [],
        'confirmation_required': False,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'nav_privacy',
        'category': 'Internal',
        'action_type': 'internal_nav',
        'display_name': 'Privacy Policy',
        'description': 'Read our privacy policy and security practices',
        'target_url': '/privacy/',
        'supported_parameters': [],
        'confirmation_required': False,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'nav_useful_links',
        'category': 'Internal',
        'action_type': 'internal_nav',
        'display_name': 'Useful Links',
        'description': 'View quick links guide',
        'target_url': '/useful-links/',
        'supported_parameters': [],
        'confirmation_required': False,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'nav_nri_services',
        'category': 'Internal',
        'action_type': 'internal_nav',
        'display_name': 'NRI Services',
        'description': 'View specialized assist guides for NRIs',
        'target_url': '/nri-assist/',
        'supported_parameters': [],
        'confirmation_required': False,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },

    # ── 2. Communication ──────────────────────────────────────────────────────
    {
        'action_name': 'call_office',
        'category': 'Communication',
        'action_type': 'phone_call',
        'display_name': 'Call Office',
        'description': 'Initiate voice call to the client desk',
        'target_url': 'tel:+918667020798',
        'supported_parameters': [],
        'confirmation_required': True,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'open_whatsapp',
        'category': 'Communication',
        'action_type': 'whatsapp',
        'display_name': 'WhatsApp Chat',
        'description': 'Open WhatsApp conversation with our advisor',
        'target_url': 'https://wa.me/918667020798',
        'supported_parameters': [],
        'confirmation_required': True,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'send_email',
        'category': 'Communication',
        'action_type': 'email',
        'display_name': 'Email Support',
        'description': 'Send email inquiry to info@propertism.in',
        'target_url': 'mailto:info@propertism.in',
        'supported_parameters': [],
        'confirmation_required': False,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'contact_advisor',
        'category': 'Communication',
        'action_type': 'phone_call',
        'display_name': 'Contact Advisor',
        'description': 'Call dedicated advisor',
        'target_url': 'tel:+918667020798',
        'supported_parameters': [],
        'confirmation_required': True,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'create_inquiry_action',
        'category': 'Communication',
        'action_type': 'inquiry_workflow',
        'display_name': 'Create Inquiry',
        'description': 'Launches interactive inquiry collection form',
        'target_url': '',
        'target_service': 'inquiry_creation',
        'supported_parameters': [],
        'confirmation_required': False,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },

    # ── 3. Location / Maps ────────────────────────────────────────────────────
    {
        'action_name': 'open_maps',
        'category': 'Location',
        'action_type': 'external_nav',
        'display_name': 'Open Google Maps',
        'description': 'Locate Propertism Office on Google Maps',
        'target_url': 'https://maps.google.com/?q=Propertism+Realty+Advisors+Chennai',
        'supported_parameters': [],
        'confirmation_required': False,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'get_directions',
        'category': 'Location',
        'action_type': 'external_nav',
        'display_name': 'Get Directions',
        'description': 'Route navigation guidance to our main office',
        'target_url': 'https://maps.google.com/?q=Propertism+Realty+Advisors+Chennai',
        'supported_parameters': [],
        'confirmation_required': False,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'nav_chennai_office',
        'category': 'Location',
        'action_type': 'external_nav',
        'display_name': 'Navigate to Chennai Office',
        'description': 'Direct maps launch for Saligramam Chennai office',
        'target_url': 'https://maps.google.com/?q=Propertism+Realty+Advisors+Chennai',
        'supported_parameters': [],
        'confirmation_required': False,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },

    # ── 4. Social ─────────────────────────────────────────────────────────────
    {
        'action_name': 'social_linkedin',
        'category': 'Social',
        'action_type': 'external_nav',
        'display_name': 'LinkedIn',
        'description': 'Visit the Propertism official LinkedIn company page',
        'target_url': 'https://www.linkedin.com/company/propertism',
        'supported_parameters': [],
        'confirmation_required': True,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },

    # ── 5. Government Services ────────────────────────────────────────────────
    {
        'action_name': 'gov_patta_chitta',
        'category': 'GovernmentServices',
        'action_type': 'external_nav',
        'display_name': 'Patta / Chitta',
        'description': 'Access official Tamil Nadu Land Records portal',
        'target_url': 'https://eservices.tn.gov.in/eservicesnew/home.html',
        'supported_parameters': [],
        'confirmation_required': True,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'gov_encumbrance',
        'category': 'GovernmentServices',
        'action_type': 'external_nav',
        'display_name': 'Encumbrance Search',
        'description': 'Verify property ownership via TNREGINET',
        'target_url': 'https://tnreginet.gov.in/',
        'supported_parameters': [],
        'confirmation_required': True,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'gov_property_tax',
        'category': 'GovernmentServices',
        'action_type': 'external_nav',
        'display_name': 'GCC Property Tax',
        'description': 'GCC online payment service for Chennai Property Tax',
        'target_url': 'https://chennaicorporation.gov.in/gcc/online-payment/property-tax/',
        'supported_parameters': [],
        'confirmation_required': True,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },

    # ── 6. Business Actions ───────────────────────────────────────────────────
    {
        'action_name': 'inquiry_launch',
        'category': 'BusinessActions',
        'action_type': 'inquiry_workflow',
        'display_name': 'Launch Inquiry',
        'description': 'Trigger start of a conversational inquiry collection',
        'target_url': '',
        'target_service': 'inquiry_creation',
        'supported_parameters': [],
        'confirmation_required': False,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'inquiry_continue',
        'category': 'BusinessActions',
        'action_type': 'inquiry_workflow',
        'display_name': 'Continue Inquiry',
        'description': 'Continue capturing details for active session',
        'target_url': '',
        'target_service': 'inquiry_creation',
        'supported_parameters': [],
        'confirmation_required': False,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'inquiry_resume',
        'category': 'BusinessActions',
        'action_type': 'inquiry_workflow',
        'display_name': 'Resume Inquiry',
        'description': 'Resume collecting info',
        'target_url': '',
        'target_service': 'inquiry_creation',
        'supported_parameters': [],
        'confirmation_required': False,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'inquiry_cancel_action',
        'category': 'BusinessActions',
        'action_type': 'inquiry_workflow',
        'display_name': 'Cancel Inquiry',
        'description': 'Cancel current session',
        'target_url': '',
        'target_service': 'inquiry_cancel',
        'supported_parameters': [],
        'confirmation_required': False,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
    {
        'action_name': 'contact_human',
        'category': 'BusinessActions',
        'action_type': 'whatsapp',
        'display_name': 'Contact Human Advisor',
        'description': 'Connect with support executive directly',
        'target_url': 'https://wa.me/918667020798',
        'supported_parameters': [],
        'confirmation_required': True,
        'security_level': 'public',
        'status': 'active',
        'version': 1,
    },
]
