# API Routing Prefix
REALBOT_API_PREFIX = "/api/v1/realbot"

# Route Endpoints
REALBOT_INIT_SESSION_PATH = f"{REALBOT_API_PREFIX}/session/init/"
REALBOT_SEND_MESSAGE_PATH = f"{REALBOT_API_PREFIX}/query/"
REALBOT_EXCHANGE_TOKEN_PATH = f"{REALBOT_API_PREFIX}/auth/exchange/"
REALBOT_HEALTH_LIVE_PATH = f"{REALBOT_API_PREFIX}/health/live/"
REALBOT_HEALTH_READY_PATH = f"{REALBOT_API_PREFIX}/health/ready/"
REALBOT_VERSION_PATH = f"{REALBOT_API_PREFIX}/version/"

# Standardized Error Catalog Codes
ERR_INTEGRATION_DISABLED = "RBOT0001"
ERR_INVALID_PARAMETERS = "RBOT0002"
ERR_SESSION_NOT_FOUND = "RBOT0003"
ERR_DATABASE_ERROR = "RBOT0004"
ERR_SERVER_CONNECTION_FAILED = "RBOT0005"
ERR_STARTUP_VALIDATION_FAILED = "RBOT0006"
ERR_MESSAGE_PROCESSING_FAILED = "RBOT0007"

# M2.14 — Security Error Codes
ERR_SECURITY_VALIDATION_FAILED = "RBOT0010"
ERR_RATE_LIMIT_EXCEEDED = "RBOT0011"
ERR_ABUSE_DETECTED = "RBOT0012"
ERR_AUTHORIZATION_DENIED = "RBOT0013"
ERR_INPUT_SANITIZATION_FAILED = "RBOT0014"
ERR_OUTPUT_VALIDATION_FAILED = "RBOT0015"

# M2.17 — Human Handover & Conversation Closure Error Codes
ERR_HANDOVER_FAILED = "RBOT0020"
ERR_ADVISOR_UNAVAILABLE = "RBOT0021"
ERR_HANDOVER_NOT_FOUND = "RBOT0022"
ERR_HANDOVER_INVALID_STATE = "RBOT0023"
ERR_ADVISOR_NOT_FOUND = "RBOT0024"
ERR_ADVISOR_NOT_AUTHORIZED = "RBOT0025"
ERR_CONVERSATION_CLOSED = "RBOT0026"
ERR_TRANSCRIPT_FAILED = "RBOT0027"
ERR_EMAIL_DISPATCH_FAILED = "RBOT0028"
ERR_ARCHIVE_FAILED = "RBOT0029"
ERR_HANDOVER_ALREADY_EXISTS = "RBOT0030"

# M2.17 — Conversation State Machine Constants
STATE_BOT_ACTIVE = 'BOT_ACTIVE'
STATE_HANDOVER_REQUESTED = 'HANDOVER_REQUESTED'
STATE_WAITING_FOR_AGENT = 'WAITING_FOR_AGENT'
STATE_AGENT_CONNECTED = 'AGENT_CONNECTED'
STATE_HUMAN_CONVERSATION = 'HUMAN_CONVERSATION'
STATE_CHAT_END_REQUESTED = 'CHAT_END_REQUESTED'
STATE_CHAT_CLOSED = 'CHAT_CLOSED'
STATE_ARCHIVED = 'ARCHIVED'

CONVERSATION_STATE_CHOICES = [
    (STATE_BOT_ACTIVE, 'Bot Active'),
    (STATE_HANDOVER_REQUESTED, 'Handover Requested'),
    (STATE_WAITING_FOR_AGENT, 'Waiting for Agent'),
    (STATE_AGENT_CONNECTED, 'Agent Connected'),
    (STATE_HUMAN_CONVERSATION, 'Human Conversation'),
    (STATE_CHAT_END_REQUESTED, 'Chat End Requested'),
    (STATE_CHAT_CLOSED, 'Chat Closed'),
    (STATE_ARCHIVED, 'Archived'),
]

MANDATORY_TRANSITIONS = {
    STATE_BOT_ACTIVE: [STATE_HANDOVER_REQUESTED],
    STATE_HANDOVER_REQUESTED: [STATE_WAITING_FOR_AGENT],
    STATE_WAITING_FOR_AGENT: [STATE_AGENT_CONNECTED],
    STATE_AGENT_CONNECTED: [STATE_HUMAN_CONVERSATION],
    STATE_HUMAN_CONVERSATION: [STATE_CHAT_END_REQUESTED],
    STATE_CHAT_END_REQUESTED: [STATE_CHAT_CLOSED],
    STATE_CHAT_CLOSED: [STATE_ARCHIVED],
    STATE_ARCHIVED: [],
}

# M2.17 — Advisor Availability States
ADVISOR_AVAILABLE = 'available'
ADVISOR_BUSY = 'busy'
ADVISOR_OFFLINE = 'offline'
ADVISOR_AWAY = 'away'

ADVISOR_STATUS_CHOICES = [
    (ADVISOR_AVAILABLE, 'Available'),
    (ADVISOR_BUSY, 'Busy'),
    (ADVISOR_OFFLINE, 'Offline'),
    (ADVISOR_AWAY, 'Away'),
]

# M2.17 — Closure Reasons
CLOSURE_CUSTOMER_INITIATED = 'customer_initiated'
CLOSURE_ADVISOR_INITIATED = 'advisor_initiated'
CLOSURE_TIMEOUT = 'timeout'
CLOSURE_SYSTEM = 'system'

CLOSURE_REASON_CHOICES = [
    (CLOSURE_CUSTOMER_INITIATED, 'Customer Initiated'),
    (CLOSURE_ADVISOR_INITIATED, 'Advisor Initiated'),
    (CLOSURE_TIMEOUT, 'Timeout'),
    (CLOSURE_SYSTEM, 'System'),
]

# M2.17 — Handover Trigger Keywords
HANDOVER_TRIGGER_KEYWORDS = [
    'talk to advisor',
    'contact advisor',
    'human assistance',
    'connect to human agent',
    'request callback',
    'escalate conversation',
    'talk to human',
    'speak to agent',
    'real person',
    'customer support',
]

# M2.17 — Default Configuration Values
DEFAULT_TRANSCRIPT_EMAIL_RECIPIENTS = 'tamil@propertism.in,propertism.tamil@gmail.com'
DEFAULT_EMAIL_ENABLED = True
DEFAULT_AGENT_HANDOVER_ENABLED = True
DEFAULT_TRANSCRIPT_SUBJECT_PREFIX = 'realBOT Conversation Transcript'
DEFAULT_EMAIL_RETRY_COUNT = 3
DEFAULT_EMAIL_TIMEOUT = 10
DEFAULT_AGENT_IDLE_TIMEOUT = 300  # 5 minutes

