"""
chat/rules_config.py — M2.4 Rule Engine Seed Configuration
Defines all 29 business intent rules. Loaded by the seed_rules management command.
Rules are ordered by priority (1=highest). Modify keywords here; re-run seed_rules.
"""

# Each entry maps directly to a BusinessRule record.
# Fields: intent, name, category, priority, positive_keywords, negative_keywords,
#         phrase_patterns, keyword_weight, min_confidence, action_type, action_config,
#         clarification_question
SEED_RULES = [

    # ── Conversation ────────────────────────────────────────────────────────
    {
        'intent': 'greeting',
        'name': 'Greeting Intent',
        'category': 'conversation',
        'priority': 1,
        'positive_keywords': 'hello,hi,hey,greetings,good morning,good afternoon,good evening,namaste,howdy,welcome',
        'negative_keywords': '',
        'phrase_patterns': 'good morning,good afternoon,good evening,hi there,hello there',
        'keyword_weight': 1.0,
        'min_confidence': 0.3,
        'action_type': 'greeting_response',
        'action_config': {
            'chips': ['Buy Property', 'Sell Property', 'NRI Services', 'Contact Us'],
        },
        'clarification_question': '',
    },
    {
        'intent': 'goodbye',
        'name': 'Goodbye Intent',
        'category': 'conversation',
        'priority': 2,
        'positive_keywords': 'bye,goodbye,farewell,see you,take care,thanks,thank you,cheers,later',
        'negative_keywords': '',
        'phrase_patterns': 'good bye,see you,thank you,thanks a lot,have a good day',
        'keyword_weight': 1.0,
        'min_confidence': 0.3,
        'action_type': 'farewell_response',
        'action_config': {
            'chips': ['Start New Query', 'Contact Us'],
        },
        'clarification_question': '',
    },

    # ── General ─────────────────────────────────────────────────────────────
    {
        'intent': 'about_propertism',
        'name': 'About Propertism Intent',
        'category': 'general',
        'priority': 5,
        'positive_keywords': 'propertism,who are you,about you,about company,describe yourself,what do you do,company,platform,service provider',
        'negative_keywords': '',
        'phrase_patterns': 'who are you,what is propertism,tell me about propertism,about propertism',
        'keyword_weight': 1.2,
        'min_confidence': 0.35,
        'action_type': 'knowledge_response',
        'action_config': {
            'source_types': ['Website'],
            'category': 'About',
            'top_k': 3,
        },
        'clarification_question': '',
    },
    {
        'intent': 'general_information',
        'name': 'General Information Intent',
        'category': 'general',
        'priority': 80,
        'positive_keywords': 'what,how,tell me,explain,information,help,know,learn,understand,details,overview',
        'negative_keywords': '',
        'phrase_patterns': 'tell me about,how does,what is,can you explain,more information',
        'keyword_weight': 0.8,
        'min_confidence': 0.3,
        'action_type': 'knowledge_response',
        'action_config': {
            'source_types': None,
            'top_k': 5,
        },
        'clarification_question': '',
    },

    # ── Contact ──────────────────────────────────────────────────────────────
    {
        'intent': 'contact_information',
        'name': 'Contact Information Intent',
        'category': 'contact',
        'priority': 10,
        'positive_keywords': 'contact,email,phone,number,reach,touch,call,write,message,enquire,get in touch',
        'negative_keywords': 'whatsapp,linkedin,google maps',
        'phrase_patterns': 'contact us,get in touch,reach out,contact details,phone number,email address',
        'keyword_weight': 1.0,
        'min_confidence': 0.4,
        'action_type': 'contact_card',
        'action_config': {
            'phone': '+91 86670 20798',
            'email': 'info@propertism.in',
            'address': 'No. 30, 3rd Floor, SSR Pankajam Towers, Arunachalam Road, Saligramam, Chennai - 600093',
            'chips': ['Call Now', 'Send WhatsApp', 'Get Directions'],
        },
        'clarification_question': '',
    },
    {
        'intent': 'office_location',
        'name': 'Office Location Intent',
        'category': 'contact',
        'priority': 11,
        'positive_keywords': 'office,location,address,where,visit,find,directions,navigate,place,situated',
        'negative_keywords': '',
        'phrase_patterns': 'office location,find us,where are you,your address,how to reach',
        'keyword_weight': 1.0,
        'min_confidence': 0.4,
        'action_type': 'google_maps',
        'action_config': {
            'maps_url': 'https://maps.google.com/?q=Propertism+Realty+Advisors+Chennai',
            'address': 'No. 30, 3rd Floor, SSR Pankajam Towers, Arunachalam Road, Saligramam, Chennai - 600093',
            'chips': ['Get Directions', 'Call Us', 'Send WhatsApp'],
        },
        'clarification_question': '',
    },
    {
        'intent': 'business_hours',
        'name': 'Business Hours Intent',
        'category': 'contact',
        'priority': 12,
        'positive_keywords': 'hours,timing,open,close,working,available,when,schedule,office hours,business hours,time',
        'negative_keywords': '',
        'phrase_patterns': 'business hours,working hours,office hours,what time,when are you open',
        'keyword_weight': 1.0,
        'min_confidence': 0.4,
        'action_type': 'knowledge_response',
        'action_config': {
            'source_types': ['Website'],
            'category': 'Contact',
            'top_k': 2,
            'fallback_text': 'Our office is open Monday to Saturday, 9:00 AM to 6:00 PM IST. '
                             'You can also reach us on WhatsApp anytime.',
        },
        'clarification_question': '',
    },

    # ── Property Services ─────────────────────────────────────────────────────
    {
        'intent': 'buy_property',
        'name': 'Buy Property Intent',
        'category': 'property',
        'priority': 20,
        'positive_keywords': 'buy,purchase,buying,invest,investing,flat,apartment,villa,property,home,house,looking for,interested in',
        'negative_keywords': 'sell,selling,rent,rental,tenant,manage',
        'phrase_patterns': 'buy property,purchase property,want to buy,looking to buy,interested in buying,invest in property',
        'keyword_weight': 1.2,
        'min_confidence': 0.4,
        'action_type': 'service_card',
        'action_config': {
            'service': 'Buy Property',
            'description': 'Propertism helps you find and secure your ideal property in Chennai. '
                           'From apartments to villas, we guide you through the entire purchase journey.',
            'url': '/services/buy-property/',
            'chips': ['View Listings', 'Schedule Viewing', 'Talk to Advisor', 'NRI Purchase'],
        },
        'clarification_question': 'Are you looking to buy a residential property or a commercial property?',
    },
    {
        'intent': 'sell_property',
        'name': 'Sell Property Intent',
        'category': 'property',
        'priority': 21,
        'positive_keywords': 'sell,selling,sale,dispose,market,seller,list,listing,price,valuation,appraisal',
        'negative_keywords': 'buy,purchase,rent,tenant,manage',
        'phrase_patterns': 'sell property,want to sell,looking to sell,property sale,market my property',
        'keyword_weight': 1.2,
        'min_confidence': 0.4,
        'action_type': 'service_card',
        'action_config': {
            'service': 'Sell Property',
            'description': 'Propertism provides expert property sale advisory including market valuation, '
                           'buyer sourcing, and end-to-end transaction support.',
            'url': '/services/sell-property/',
            'chips': ['Get Valuation', 'List My Property', 'Talk to Advisor'],
        },
        'clarification_question': '',
    },
    {
        'intent': 'rental_income',
        'name': 'Rental Income Management Intent',
        'category': 'property',
        'priority': 22,
        'positive_keywords': 'rent,rental,tenant,manage,income,collect,renting,lease,landlord,property management,property manager',
        'negative_keywords': 'buy,sell,purchase,sale',
        'phrase_patterns': 'property management,rent collection,manage my property,rental management,find tenant',
        'keyword_weight': 1.1,
        'min_confidence': 0.4,
        'action_type': 'service_card',
        'action_config': {
            'service': 'Rental Income Management',
            'description': 'Propertism manages your property end-to-end — tenant sourcing, rent collection, '
                           'maintenance, and monthly reporting.',
            'url': '/services/property-management/',
            'chips': ['Tenant Sourcing', 'Rent Collection', 'Maintenance', 'NRI Management'],
        },
        'clarification_question': '',
    },
    {
        'intent': 'land_plot',
        'name': 'Land / Plot Services Intent',
        'category': 'property',
        'priority': 23,
        'positive_keywords': 'plot,land,site,acre,layout,residential plot,open plot,land purchase',
        'negative_keywords': 'apartment,flat,villa,house',
        'phrase_patterns': 'buy plot,purchase land,residential plot,land for sale,open plot',
        'keyword_weight': 1.1,
        'min_confidence': 0.4,
        'action_type': 'service_card',
        'action_config': {
            'service': 'Land & Plot Services',
            'description': 'Propertism assists with land and plot purchase, document verification, '
                           'patta/chitta assistance, and EC search.',
            'url': '/services/land-plots/',
            'chips': ['View Available Plots', 'Document Help', 'Talk to Advisor'],
        },
        'clarification_question': '',
    },
    {
        'intent': 'property_search',
        'name': 'Property Search Intent',
        'category': 'property',
        'priority': 24,
        'positive_keywords': 'search,find,available,list,listings,show,browse,properties,options,inventory',
        'negative_keywords': 'sell,selling',
        'phrase_patterns': 'show me properties,find properties,available properties,property list',
        'keyword_weight': 1.0,
        'min_confidence': 0.35,
        'action_type': 'service_card',
        'action_config': {
            'service': 'Property Search',
            'description': 'Browse our curated property inventory across Chennai including apartments, '
                           'villas, plots, and commercial spaces.',
            'url': '/properties/',
            'chips': ['Apartments', 'Villas', 'Plots', 'Filter by Budget'],
        },
        'clarification_question': 'Are you looking for a residential property, commercial space, or a plot?',
    },
    {
        'intent': 'property_viewing',
        'name': 'Property Viewing Intent',
        'category': 'property',
        'priority': 25,
        'positive_keywords': 'visit,viewing,site visit,schedule,appointment,see property,tour,inspection',
        'negative_keywords': '',
        'phrase_patterns': 'schedule visit,site visit,property viewing,book appointment,arrange viewing',
        'keyword_weight': 1.1,
        'min_confidence': 0.4,
        'action_type': 'service_card',
        'action_config': {
            'service': 'Schedule Property Viewing',
            'description': 'Schedule a guided property visit with one of our advisors at your convenience.',
            'url': '/contact/',
            'chips': ['Book Visit', 'Call Us', 'Send WhatsApp'],
        },
        'clarification_question': '',
    },

    # ── NRI ──────────────────────────────────────────────────────────────────
    {
        'intent': 'nri_assist',
        'name': 'NRI Assist Intent',
        'category': 'nri',
        'priority': 15,
        'positive_keywords': 'nri,overseas,abroad,oci,foreign,non-resident,remit,repatriation,fema,pio,international',
        'negative_keywords': '',
        'phrase_patterns': 'nri investment,nri property,nri services,overseas investor,non resident indian',
        'keyword_weight': 1.3,
        'min_confidence': 0.35,
        'action_type': 'service_card',
        'action_config': {
            'service': 'NRI Property Services',
            'description': 'Propertism specialises in NRI property management, acquisition, '
                           'and sale with full FEMA and RBI compliance.',
            'url': '/services/nri/',
            'chips': ['NRI Property Management', 'NRI Investment', 'FEMA Guidance', 'Contact NRI Desk'],
        },
        'clarification_question': '',
    },

    # ── Resources ─────────────────────────────────────────────────────────────
    {
        'intent': 'resource_hub',
        'name': 'Resource Hub Intent',
        'category': 'resources',
        'priority': 30,
        'positive_keywords': 'resource,article,guide,blog,read,content,knowledge,tips,advice,learn',
        'negative_keywords': '',
        'phrase_patterns': 'resource hub,knowledge hub,read articles,property guide,investment guide',
        'keyword_weight': 1.0,
        'min_confidence': 0.35,
        'action_type': 'navigation_card',
        'action_config': {
            'label': 'Resource Hub',
            'url': '/resource-hub/',
            'description': 'Access our curated library of property guides, NRI investment articles, '
                           'and market insights.',
            'chips': ['NRI Articles', 'Buying Guide', 'Legal Guides'],
        },
        'clarification_question': '',
    },
    {
        'intent': 'useful_links',
        'name': 'Useful Links Intent',
        'category': 'resources',
        'priority': 31,
        'positive_keywords': 'links,useful,tools,external,portal,government,tnreginet,guideline,resources',
        'negative_keywords': '',
        'phrase_patterns': 'useful links,government portal,land records,registration',
        'keyword_weight': 1.0,
        'min_confidence': 0.35,
        'action_type': 'navigation_card',
        'action_config': {
            'label': 'Useful Links',
            'url': '/useful-links/',
            'description': 'Access useful government portals and external resources including TNREGINET, '
                           'GCC Tax Portal, and more.',
            'chips': ['TNREGINET', 'GCC Tax', 'Encumbrance', 'Patta Chitta'],
        },
        'clarification_question': '',
    },

    # ── FAQ & Legal ───────────────────────────────────────────────────────────
    {
        'intent': 'faq',
        'name': 'FAQ Intent',
        'category': 'faq',
        'priority': 32,
        'positive_keywords': 'faq,frequently,question,common,asked,doubt,clarify,explain',
        'negative_keywords': '',
        'phrase_patterns': 'frequently asked questions,common questions,have a question',
        'keyword_weight': 1.0,
        'min_confidence': 0.35,
        'action_type': 'knowledge_response',
        'action_config': {
            'source_types': ['FAQ', 'Website'],
            'top_k': 3,
        },
        'clarification_question': '',
    },
    {
        'intent': 'terms_conditions',
        'name': 'Terms and Conditions Intent',
        'category': 'legal',
        'priority': 33,
        'positive_keywords': 'terms,conditions,legal,agreement,clauses,contract,policy,binding,rules,regulation',
        'negative_keywords': '',
        'phrase_patterns': 'terms and conditions,service agreement,terms of service,legal terms',
        'keyword_weight': 1.2,
        'min_confidence': 0.4,
        'action_type': 'knowledge_response',
        'action_config': {
            'source_types': ['Terms'],
            'top_k': 3,
        },
        'clarification_question': '',
    },
    {
        'intent': 'fee_structure',
        'name': 'Service Fee Structure Intent',
        'category': 'financial',
        'priority': 34,
        'positive_keywords': 'fee,fees,charge,charges,commission,pricing,cost,costs,rate,rates,price,payment,remuneration',
        'negative_keywords': 'no fee,free,waive',
        'phrase_patterns': 'fee structure,service charge,management fee,commission rate,how much do you charge',
        'keyword_weight': 1.2,
        'min_confidence': 0.4,
        'action_type': 'knowledge_response',
        'action_config': {
            'source_types': ['FeeStructure'],
            'top_k': 3,
        },
        'clarification_question': 'Are you asking about property management fees, tenant sourcing fees, or sale commission?',
    },

    # ── Government Portals ────────────────────────────────────────────────────
    {
        'intent': 'patta_chitta',
        'name': 'Patta / Chitta Intent',
        'category': 'legal',
        'priority': 40,
        'positive_keywords': 'patta,chitta,land record,title deed,ownership,document,tamilnadu,tnreginet',
        'negative_keywords': '',
        'phrase_patterns': 'patta chitta,land records,ownership document,tnreginet',
        'keyword_weight': 1.2,
        'min_confidence': 0.4,
        'action_type': 'navigation_card',
        'action_config': {
            'label': 'Patta / Chitta Portal',
            'url': 'https://eservices.tn.gov.in/',
            'description': 'Access the Tamil Nadu government portal to view and download '
                           'Patta and Chitta land records.',
            'chips': ['Open Portal', 'What is Patta?', 'Get Help'],
        },
        'clarification_question': '',
    },
    {
        'intent': 'encumbrance_search',
        'name': 'Encumbrance Search Intent',
        'category': 'legal',
        'priority': 41,
        'positive_keywords': 'encumbrance,ec,certificate,loan,mortgage,lien,charge,pending,bank,dues',
        'negative_keywords': '',
        'phrase_patterns': 'encumbrance certificate,ec search,property ec,check encumbrance',
        'keyword_weight': 1.2,
        'min_confidence': 0.4,
        'action_type': 'navigation_card',
        'action_config': {
            'label': 'Encumbrance Certificate Portal',
            'url': 'https://tnreginet.gov.in/',
            'description': 'Search for property encumbrance certificates through the TNREGINET portal.',
            'chips': ['Open TNREGINET', 'What is EC?', 'Get Help'],
        },
        'clarification_question': '',
    },
    {
        'intent': 'gcc_property_tax',
        'name': 'GCC Property Tax Intent',
        'category': 'legal',
        'priority': 42,
        'positive_keywords': 'gcc,property tax,tax,municipality,corporation,chennai tax,tax payment,tax dues',
        'negative_keywords': '',
        'phrase_patterns': 'gcc property tax,pay property tax,property tax chennai,check tax',
        'keyword_weight': 1.2,
        'min_confidence': 0.4,
        'action_type': 'navigation_card',
        'action_config': {
            'label': 'GCC Property Tax Portal',
            'url': 'https://chennaicorporation.gov.in/',
            'description': 'Pay or check your Greater Chennai Corporation (GCC) property tax online.',
            'chips': ['Open GCC Portal', 'Check Tax Dues', 'Get Help'],
        },
        'clarification_question': '',
    },

    # ── Action Intents ────────────────────────────────────────────────────────
    {
        'intent': 'whatsapp',
        'name': 'WhatsApp Intent',
        'category': 'action',
        'priority': 50,
        'positive_keywords': 'whatsapp,wa,message,chat,text,connect',
        'negative_keywords': 'call,phone',
        'phrase_patterns': 'send whatsapp,message us,chat on whatsapp,whatsapp us',
        'keyword_weight': 1.5,
        'min_confidence': 0.45,
        'action_type': 'whatsapp',
        'action_config': {
            'phone': '+918667020798',
            'message': 'Hello Propertism, I would like to enquire about your services.',
            'chips': ['Open WhatsApp', 'Call Instead'],
        },
        'clarification_question': '',
    },
    {
        'intent': 'phone_call',
        'name': 'Phone Call Intent',
        'category': 'action',
        'priority': 51,
        'positive_keywords': 'call,phone,speak,ring,telephone,dial,talk',
        'negative_keywords': 'whatsapp,message',
        'phrase_patterns': 'call us,phone call,speak to someone,give us a call',
        'keyword_weight': 1.5,
        'min_confidence': 0.45,
        'action_type': 'phone_call',
        'action_config': {
            'phone': '+91 86670 20798',
            'chips': ['Call Now', 'Send WhatsApp'],
        },
        'clarification_question': '',
    },
    {
        'intent': 'google_maps',
        'name': 'Google Maps Intent',
        'category': 'action',
        'priority': 52,
        'positive_keywords': 'directions,map,navigate,find us,google maps,maps,route,gps,location',
        'negative_keywords': '',
        'phrase_patterns': 'google maps,get directions,show on map,navigate to',
        'keyword_weight': 1.3,
        'min_confidence': 0.45,
        'action_type': 'google_maps',
        'action_config': {
            'maps_url': 'https://maps.google.com/?q=Propertism+Realty+Advisors+Chennai',
            'chips': ['Open Maps', 'Get Directions'],
        },
        'clarification_question': '',
    },
    {
        'intent': 'linkedin',
        'name': 'LinkedIn Intent',
        'category': 'action',
        'priority': 53,
        'positive_keywords': 'linkedin,social,follow,connect,professional,network,profile',
        'negative_keywords': '',
        'phrase_patterns': 'follow on linkedin,linkedin profile,connect on linkedin',
        'keyword_weight': 1.3,
        'min_confidence': 0.45,
        'action_type': 'external_link',
        'action_config': {
            'url': 'https://www.linkedin.com/company/propertism',
            'label': 'Propertism on LinkedIn',
            'chips': ['Follow Us', 'View Profile'],
        },
        'clarification_question': '',
    },

    # ── Inquiry & Escalation ──────────────────────────────────────────────────
    {
        'intent': 'inquiry_creation',
        'name': 'Inquiry Creation Intent',
        'category': 'inquiry',
        'priority': 60,
        'positive_keywords': 'inquiry,enquiry,interested,request,submit,form,register,quote,proposal',
        'negative_keywords': '',
        'phrase_patterns': 'submit inquiry,create inquiry,send inquiry,make an enquiry,i am interested',
        'keyword_weight': 1.2,
        'min_confidence': 0.4,
        'action_type': 'inquiry_workflow',
        'action_config': {
            'chips': ['Submit Inquiry', 'Talk to Advisor', 'Call Us'],
        },
        'clarification_question': '',
    },
    {
        'intent': 'human_assistance',
        'name': 'Human Assistance Intent',
        'category': 'escalation',
        'priority': 61,
        'positive_keywords': 'agent,human,person,staff,advisor,speak,representative,escalate,manager,support,assistance',
        'negative_keywords': '',
        'phrase_patterns': 'speak to someone,talk to human,connect to advisor,human agent,need help',
        'keyword_weight': 1.3,
        'min_confidence': 0.4,
        'action_type': 'contact_card',
        'action_config': {
            'phone': '+91 86670 20798',
            'email': 'info@propertism.in',
            'message': "I'll connect you with one of our advisors. You can reach us immediately "
                       "via phone or WhatsApp.",
            'chips': ['Call Now', 'Send WhatsApp', 'Send Email'],
        },
        'clarification_question': '',
    },

    # ── Catch-All Fallback ────────────────────────────────────────────────────
    {
        'intent': 'unknown_intent',
        'name': 'Unknown Intent Fallback',
        'category': 'fallback',
        'priority': 99,
        'positive_keywords': '',
        'negative_keywords': '',
        'phrase_patterns': '',
        'keyword_weight': 0.0,
        'min_confidence': 0.0,
        'action_type': 'fallback_response',
        'action_config': {
            'chips': ['Buy Property', 'Sell Property', 'NRI Services', 'Contact Us'],
        },
        'clarification_question': '',
    },
]
