"""
chat/suggestions_config.py — Predefined Suggestion Registry Configuration (M2.7)

Contains definitions for initial seeding.
Every suggestion has a unique, immutable reference suggestion_id.
"""

SEED_SUGGESTIONS = [
    # ── 1. Welcome Suggestions ────────────────────────────────────────────────
    {
        'display_text': 'Explore Services',
        'category': 'Welcome',
        'trigger_condition': {'intent': 'greeting'},
        'business_intent': 'about_propertism',
        'target_action': '/services',
        'display_priority': 10,
        'icon': 'info',
        'display_order': 1,
    },
    {
        'display_text': 'Buy Property',
        'category': 'Welcome',
        'trigger_condition': {'intent': 'greeting'},
        'business_intent': 'buy_property',
        'target_action': 'inquiry_creation',
        'display_priority': 10,
        'icon': 'home',
        'display_order': 2,
    },
    {
        'display_text': 'NRI Services',
        'category': 'Welcome',
        'trigger_condition': {'intent': 'greeting'},
        'business_intent': 'nri_assist',
        'target_action': 'inquiry_creation',
        'display_priority': 10,
        'icon': 'globe',
        'display_order': 3,
    },
    {
        'display_text': 'Contact Advisor',
        'category': 'Welcome',
        'trigger_condition': {'intent': 'greeting'},
        'business_intent': 'human_assistance',
        'target_action': 'phone_call',
        'display_priority': 15,
        'icon': 'phone',
        'display_order': 4,
    },

    # ── 2. Quick Inquiry Journey Suggestions ──────────────────────────────────
    {
        'display_text': 'Buy Property',
        'category': 'Inquiry',
        'trigger_condition': {'intent': 'inquiry_creation', 'inquiry_state': 'not_started'},
        'business_intent': 'buy_property',
        'target_action': 'inquiry_creation',
        'display_priority': 20,
        'icon': 'home',
        'display_order': 1,
    },
    {
        'display_text': 'Sell Property',
        'category': 'Inquiry',
        'trigger_condition': {'intent': 'inquiry_creation', 'inquiry_state': 'not_started'},
        'business_intent': 'sell_property',
        'target_action': 'inquiry_creation',
        'display_priority': 20,
        'icon': 'dollar-sign',
        'display_order': 2,
    },
    {
        'display_text': 'Rental Income Management',
        'category': 'Inquiry',
        'trigger_condition': {'intent': 'inquiry_creation', 'inquiry_state': 'not_started'},
        'business_intent': 'rental_income',
        'target_action': 'inquiry_creation',
        'display_priority': 20,
        'icon': 'key',
        'display_order': 3,
    },
    {
        'display_text': 'Land / Plot Services',
        'category': 'Inquiry',
        'trigger_condition': {'intent': 'inquiry_creation', 'inquiry_state': 'not_started'},
        'business_intent': 'land_plot',
        'target_action': 'inquiry_creation',
        'display_priority': 20,
        'icon': 'map',
        'display_order': 4,
    },
    {
        'display_text': 'Property Search',
        'category': 'Inquiry',
        'trigger_condition': {'intent': 'inquiry_creation', 'inquiry_state': 'not_started'},
        'business_intent': 'property_search',
        'target_action': 'inquiry_creation',
        'display_priority': 25,
        'icon': 'search',
        'display_order': 5,
    },
    {
        'display_text': 'Property Viewing',
        'category': 'Inquiry',
        'trigger_condition': {'intent': 'inquiry_creation', 'inquiry_state': 'not_started'},
        'business_intent': 'property_viewing',
        'target_action': 'inquiry_creation',
        'display_priority': 25,
        'icon': 'eye',
        'display_order': 6,
    },
    {
        'display_text': 'NRI Assist',
        'category': 'Inquiry',
        'trigger_condition': {'intent': 'inquiry_creation', 'inquiry_state': 'not_started'},
        'business_intent': 'nri_assist',
        'target_action': 'inquiry_creation',
        'display_priority': 25,
        'icon': 'globe',
        'display_order': 7,
    },
    {
        'display_text': 'Patta / Chitta',
        'category': 'GovernmentService',
        'trigger_condition': {'intent': 'inquiry_creation', 'inquiry_state': 'not_started'},
        'business_intent': 'patta_chitta',
        'target_action': 'inquiry_creation',
        'display_priority': 30,
        'icon': 'file-text',
        'display_order': 8,
    },
    {
        'display_text': 'Encumbrance Search',
        'category': 'GovernmentService',
        'trigger_condition': {'intent': 'inquiry_creation', 'inquiry_state': 'not_started'},
        'business_intent': 'encumbrance_search',
        'target_action': 'inquiry_creation',
        'display_priority': 30,
        'icon': 'shield',
        'display_order': 9,
    },
    {
        'display_text': 'GCC Property Tax',
        'category': 'GovernmentService',
        'trigger_condition': {'intent': 'inquiry_creation', 'inquiry_state': 'not_started'},
        'business_intent': 'gcc_property_tax',
        'target_action': 'inquiry_creation',
        'display_priority': 30,
        'icon': 'percent',
        'display_order': 10,
    },
    {
        'display_text': 'General Advisory',
        'category': 'Inquiry',
        'trigger_condition': {'intent': 'inquiry_creation', 'inquiry_state': 'not_started'},
        'business_intent': 'general_information',
        'target_action': 'inquiry_creation',
        'display_priority': 35,
        'icon': 'message-circle',
        'display_order': 11,
    },
    {
        'display_text': 'Contact Advisor',
        'category': 'Contact',
        'trigger_condition': {'intent': 'inquiry_creation', 'inquiry_state': 'not_started'},
        'business_intent': 'human_assistance',
        'target_action': 'phone_call',
        'display_priority': 35,
        'icon': 'phone',
        'display_order': 12,
    },

    # ── 3. Page-Specific Suggestions ──────────────────────────────────────────
    {
        'display_text': 'View NRI Guide',
        'category': 'Navigation',
        'trigger_condition': {'page': '/nri-assist'},
        'business_intent': 'nri_assist',
        'target_action': '/nri-assist/guide',
        'display_priority': 10,
        'icon': 'file-text',
        'display_order': 1,
    },
    {
        'display_text': 'NRI Callback Request',
        'category': 'Contact',
        'trigger_condition': {'page': '/nri-assist'},
        'business_intent': 'inquiry_creation',
        'target_action': 'inquiry_creation',
        'display_priority': 10,
        'icon': 'phone-call',
        'display_order': 2,
    },
    {
        'display_text': 'Filter Properties',
        'category': 'Navigation',
        'trigger_condition': {'page': '/properties'},
        'business_intent': 'property_search',
        'target_action': '/properties/search',
        'display_priority': 10,
        'icon': 'sliders',
        'display_order': 1,
    },

    # ── 4. Service Profile-Specific Suggestions (CTAs) ────────────────────────
    {
        'display_text': 'Check Eligibility',
        'category': 'Service',
        'trigger_condition': {'service_profile': 'NRI Property Management'},
        'business_intent': 'nri_assist',
        'target_action': 'eligibility',
        'display_priority': 10,
        'icon': 'check-circle',
        'display_order': 1,
    },
    {
        'display_text': 'Request Service Consultation',
        'category': 'Service',
        'trigger_condition': {'service_profile': 'NRI Property Management'},
        'business_intent': 'inquiry_creation',
        'target_action': 'inquiry_creation',
        'display_priority': 10,
        'icon': 'calendar',
        'display_order': 2,
    },

    # ── 5. Knowledge Response Follow-ups ──────────────────────────────────────
    {
        'display_text': 'Read Documentation',
        'category': 'Knowledge',
        'trigger_condition': {'knowledge_resolved': True},
        'business_intent': 'useful_links',
        'target_action': 'knowledge_docs',
        'display_priority': 40,
        'icon': 'book-open',
        'display_order': 1,
    },
    {
        'display_text': 'Ask for Advisor',
        'category': 'Contact',
        'trigger_condition': {'knowledge_resolved': True},
        'business_intent': 'human_assistance',
        'target_action': 'phone_call',
        'display_priority': 45,
        'icon': 'user',
        'display_order': 2,
    },

    # ── 6. Conversation Recovery / Fallback ──────────────────────────────────
    {
        'display_text': 'Restart Conversation',
        'category': 'Recovery',
        'trigger_condition': {'intent': 'unknown_intent'},
        'business_intent': 'greeting',
        'target_action': 'restart',
        'display_priority': 50,
        'icon': 'rotate-ccw',
        'display_order': 1,
    },
    {
        'display_text': 'Talk to Support',
        'category': 'Contact',
        'trigger_condition': {'intent': 'unknown_intent'},
        'business_intent': 'human_assistance',
        'target_action': 'whatsapp',
        'display_priority': 55,
        'icon': 'message-square',
        'display_order': 2,
    },

    # ── 7. Completion Suggestions ─────────────────────────────────────────────
    {
        'display_text': 'Track Inquiry Status',
        'category': 'Completion',
        'trigger_condition': {'inquiry_state': 'submitted'},
        'business_intent': 'general_information',
        'target_action': '/inquiries/',
        'display_priority': 5,
        'icon': 'activity',
        'display_order': 1,
    },
    {
        'display_text': 'New Inquiry',
        'category': 'Completion',
        'trigger_condition': {'inquiry_state': 'submitted'},
        'business_intent': 'inquiry_creation',
        'target_action': 'inquiry_creation',
        'display_priority': 5,
        'icon': 'plus-circle',
        'display_order': 2,
    },
    {
        'display_text': 'Browse Properties',
        'category': 'Completion',
        'trigger_condition': {'inquiry_state': 'submitted'},
        'business_intent': 'property_search',
        'target_action': '/properties',
        'display_priority': 8,
        'icon': 'grid',
        'display_order': 3,
    },
]
