# Generated by Django 5.2.6 on 2026-07-06 14:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="realbotsession",
            name="conversation_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
