# Generated by Django 5.2.6 on 2026-07-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_realbotsession_conversation_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_title", models.CharField(max_length=500)),
                ("url", models.CharField(blank=True, max_length=1000)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Service", "Service"),
                            ("FAQ", "FAQ"),
                            ("Blog", "Blog"),
                            ("NRI", "NRI"),
                            ("About", "About"),
                            ("Contact", "Contact"),
                            ("Property", "Property"),
                            ("General", "General"),
                        ],
                        default="General",
                        max_length=30,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "keywords",
                    models.TextField(
                        blank=True, help_text="Space or comma-separated keyword terms"
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("main_content", models.TextField(blank=True)),
                ("last_modified", models.DateTimeField(blank=True, null=True)),
                (
                    "published_status",
                    models.CharField(
                        choices=[
                            ("published", "Published"),
                            ("draft", "Draft"),
                            ("hidden", "Hidden"),
                        ],
                        default="published",
                        max_length=20,
                    ),
                ),
                (
                    "search_weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Multiplier applied during relevance scoring",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("Website", "Website"),
                            ("Markdown", "Markdown"),
                            ("Policy", "Policy"),
                            ("FAQ", "FAQ"),
                        ],
                        default="Website",
                        max_length=30,
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        help_text="e.g., Service:property-management",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("indexed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Knowledge Article",
                "verbose_name_plural": "Knowledge Articles",
                "ordering": ["-search_weight", "page_title"],
                "indexes": [
                    models.Index(
                        fields=["source_type", "category"],
                        name="chat_knowle_source__5bd17e_idx",
                    ),
                    models.Index(
                        fields=["published_status"],
                        name="chat_knowle_publish_22d8b7_idx",
                    ),
                ],
            },
        ),
    ]
