# Generated by Django 5.2.6 on 2026-07-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_knowledge_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgearticle",
            name="knowledge_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stable, immutable identifier e.g. KA000001. Auto-generated on creation.",
                max_length=20,
                unique=True,
            ),
        ),
    ]
