# Generated by Django 5.2.6 on 2026-07-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_add_knowledge_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable, immutable document identifier e.g. DOC000001.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "doc_slug",
                    models.SlugField(
                        help_text="URL-safe document identifier e.g. terms-and-conditions",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Filename relative to chat/knowledge_docs/ e.g. terms-and-conditions.md",
                        max_length=500,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("Website", "Website"),
                            ("Markdown", "Markdown"),
                            ("Policy", "Policy"),
                            ("FAQ", "FAQ"),
                            ("Terms", "Terms & Conditions"),
                            ("FeeStructure", "Fee Structure"),
                        ],
                        default="Markdown",
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Service", "Service"),
                            ("FAQ", "FAQ"),
                            ("Blog", "Blog"),
                            ("NRI", "NRI"),
                            ("About", "About"),
                            ("Contact", "Contact"),
                            ("Property", "Property"),
                            ("General", "General"),
                        ],
                        default="General",
                        max_length=30,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "tags",
                    models.TextField(
                        blank=True, help_text="Comma-separated tags for filtering"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Increments each time file content changes"
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 of file content for change detection",
                        max_length=64,
                    ),
                ),
                (
                    "published_status",
                    models.CharField(
                        choices=[
                            ("published", "Published"),
                            ("draft", "Draft"),
                            ("hidden", "Hidden"),
                        ],
                        default="published",
                        max_length=20,
                    ),
                ),
                (
                    "section_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of KnowledgeArticle sections currently indexed",
                    ),
                ),
                ("indexed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Knowledge Document",
                "verbose_name_plural": "Knowledge Documents",
                "ordering": ["source_type", "title"],
            },
        ),
        migrations.AlterField(
            model_name="knowledgearticle",
            name="source_ref",
            field=models.CharField(
                help_text="e.g., Website:service:property-management",
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgearticle",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("Website", "Website"),
                    ("Markdown", "Markdown"),
                    ("Policy", "Policy"),
                    ("FAQ", "FAQ"),
                    ("Terms", "Terms & Conditions"),
                    ("FeeStructure", "Fee Structure"),
                ],
                default="Website",
                max_length=30,
            ),
        ),
    ]
