# Generated by Django 5.2.6 on 2026-07-06 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_m23_knowledge_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable immutable identifier e.g. RBR000001.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("greeting", "Greeting"),
                            ("goodbye", "Goodbye"),
                            ("general_information", "General Information"),
                            ("about_propertism", "About Propertism"),
                            ("contact_information", "Contact Information"),
                            ("office_location", "Office Location"),
                            ("business_hours", "Business Hours"),
                            ("buy_property", "Buy Property"),
                            ("sell_property", "Sell Property"),
                            ("rental_income", "Rental Income Management"),
                            ("land_plot", "Land / Plot Services"),
                            ("property_search", "Property Search"),
                            ("property_viewing", "Property Viewing"),
                            ("nri_assist", "NRI Assist"),
                            ("resource_hub", "Resource Hub"),
                            ("useful_links", "Useful Links"),
                            ("faq", "FAQ"),
                            ("terms_conditions", "Terms and Conditions"),
                            ("fee_structure", "Service Fee Structure"),
                            ("patta_chitta", "Patta / Chitta"),
                            ("encumbrance_search", "Encumbrance Search"),
                            ("gcc_property_tax", "GCC Property Tax"),
                            ("whatsapp", "WhatsApp"),
                            ("phone_call", "Phone Call"),
                            ("google_maps", "Google Maps"),
                            ("linkedin", "LinkedIn"),
                            ("inquiry_creation", "Inquiry Creation"),
                            ("human_assistance", "Human Assistance"),
                            ("unknown_intent", "Unknown Intent"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("conversation", "Conversation"),
                            ("general", "General"),
                            ("contact", "Contact"),
                            ("property", "Property"),
                            ("nri", "NRI"),
                            ("resources", "Resources"),
                            ("faq", "FAQ"),
                            ("legal", "Legal"),
                            ("financial", "Financial"),
                            ("action", "Action"),
                            ("inquiry", "Inquiry"),
                            ("escalation", "Escalation"),
                            ("fallback", "Fallback"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Lower = higher priority. 1=highest, 99=catch-all fallback.",
                    ),
                ),
                (
                    "positive_keywords",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated keywords that raise confidence when matched.",
                    ),
                ),
                (
                    "negative_keywords",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated keywords that lower confidence when matched.",
                    ),
                ),
                (
                    "phrase_patterns",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated exact multi-word phrases (weighted 3x over keywords).",
                    ),
                ),
                ("keyword_weight", models.FloatField(default=1.0)),
                ("min_confidence", models.FloatField(default=0.4)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("knowledge_response", "Return Knowledge Response"),
                            ("service_card", "Return Service Card"),
                            ("navigation_card", "Return Navigation Card"),
                            ("contact_card", "Return Contact Card"),
                            ("inquiry_workflow", "Launch Inquiry Workflow"),
                            ("external_link", "Open External Link"),
                            ("google_maps", "Open Google Maps"),
                            ("whatsapp", "Open WhatsApp"),
                            ("phone_call", "Initiate Phone Call"),
                            ("related_services", "Suggest Related Services"),
                            ("clarification", "Request Clarification"),
                            ("fallback_response", "Return Fallback Response"),
                            ("greeting_response", "Return Greeting Response"),
                            ("farewell_response", "Return Farewell Response"),
                        ],
                        max_length=30,
                    ),
                ),
                ("action_config", models.JSONField(default=dict)),
                ("is_enabled", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("allow_chain", models.BooleanField(default=False)),
                ("clarification_question", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Business Rule",
                "verbose_name_plural": "Business Rules",
                "ordering": ["priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["intent"], name="chat_busine_intent_01c64b_idx"
                    ),
                    models.Index(
                        fields=["is_enabled", "priority"],
                        name="chat_busine_is_enab_c7f300_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RuleExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable log identifier e.g. REL000001.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("session_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("query", models.TextField()),
                (
                    "resolved_intent",
                    models.CharField(
                        choices=[
                            ("greeting", "Greeting"),
                            ("goodbye", "Goodbye"),
                            ("general_information", "General Information"),
                            ("about_propertism", "About Propertism"),
                            ("contact_information", "Contact Information"),
                            ("office_location", "Office Location"),
                            ("business_hours", "Business Hours"),
                            ("buy_property", "Buy Property"),
                            ("sell_property", "Sell Property"),
                            ("rental_income", "Rental Income Management"),
                            ("land_plot", "Land / Plot Services"),
                            ("property_search", "Property Search"),
                            ("property_viewing", "Property Viewing"),
                            ("nri_assist", "NRI Assist"),
                            ("resource_hub", "Resource Hub"),
                            ("useful_links", "Useful Links"),
                            ("faq", "FAQ"),
                            ("terms_conditions", "Terms and Conditions"),
                            ("fee_structure", "Service Fee Structure"),
                            ("patta_chitta", "Patta / Chitta"),
                            ("encumbrance_search", "Encumbrance Search"),
                            ("gcc_property_tax", "GCC Property Tax"),
                            ("whatsapp", "WhatsApp"),
                            ("phone_call", "Phone Call"),
                            ("google_maps", "Google Maps"),
                            ("linkedin", "LinkedIn"),
                            ("inquiry_creation", "Inquiry Creation"),
                            ("human_assistance", "Human Assistance"),
                            ("unknown_intent", "Unknown Intent"),
                        ],
                        default="unknown_intent",
                        max_length=50,
                    ),
                ),
                ("confidence_score", models.FloatField(default=0.0)),
                ("rules_evaluated", models.IntegerField(default=0)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("resolved", "Resolved"),
                            ("clarification", "Clarification"),
                            ("fallback", "Fallback"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("execution_time_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_logs",
                        to="chat.businessrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule Execution Log",
                "verbose_name_plural": "Rule Execution Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
