# Generated by Django 5.2.6 on 2026-07-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_m24_rule_engine"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable, immutable service identifier e.g. SRV000001.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(max_length=100)),
                ("short_description", models.TextField()),
                ("detailed_description", models.TextField()),
                ("business_objective", models.TextField()),
                ("target_audience", models.TextField()),
                (
                    "eligibility",
                    models.TextField(
                        blank=True, help_text="Eligibility rules / criteria"
                    ),
                ),
                (
                    "required_inputs",
                    models.TextField(
                        blank=True, help_text="Required documents / inputs"
                    ),
                ),
                (
                    "advisory_content",
                    models.JSONField(
                        default=dict,
                        help_text="Advisory details including overview, benefits, process, pricing, and limitations.",
                    ),
                ),
                (
                    "faqs",
                    models.JSONField(default=list, help_text="List of inline FAQs"),
                ),
                (
                    "knowledge_references",
                    models.CharField(
                        blank=True,
                        help_text="Search terms to query Unified Knowledge Repository for this service",
                        max_length=255,
                    ),
                ),
                (
                    "related_services",
                    models.JSONField(
                        default=list, help_text="List of related Service IDs"
                    ),
                ),
                (
                    "call_to_actions",
                    models.JSONField(
                        default=list, help_text="Call-to-action actions / suggestions"
                    ),
                ),
                (
                    "contact_channels",
                    models.JSONField(
                        default=list,
                        help_text="Allowed contact channels for this service",
                    ),
                ),
                (
                    "escalation_rules",
                    models.JSONField(default=dict, help_text="Escalation pathways"),
                ),
                (
                    "navigation_links",
                    models.JSONField(
                        default=list, help_text="Key web page navigation URLs"
                    ),
                ),
                ("display_priority", models.PositiveIntegerField(default=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service Profile",
                "verbose_name_plural": "Service Profiles",
                "ordering": ["display_priority", "name"],
            },
        ),
    ]
