# Generated by Django 5.2.6 on 2026-07-07 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_m25_service_coverage"),
    ]

    operations = [
        migrations.CreateModel(
            name="InquiryConversationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ics_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable, immutable identifier e.g. ICS000001.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("collecting_information", "Collecting Information"),
                            (
                                "awaiting_conflict_resolution",
                                "Awaiting Conflict Resolution",
                            ),
                            ("awaiting_confirmation", "Awaiting Confirmation"),
                            ("submitted", "Submitted"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="collecting_information",
                        max_length=40,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual_chat", "Manual Chat Request"),
                            ("service_profile_cta", "Service Profile CTA"),
                            ("rule_engine", "Rule Engine Intent"),
                            ("suggestion_chip", "Suggestion Chip"),
                            ("website_entry_point", "Website Entry Point"),
                        ],
                        default="manual_chat",
                        max_length=30,
                    ),
                ),
                (
                    "service_hint",
                    models.CharField(
                        blank=True,
                        help_text="Service intent from triggering context e.g. 'sell_property'.",
                        max_length=100,
                    ),
                ),
                ("collected_data", models.JSONField(default=dict)),
                ("skipped_fields", models.JSONField(default=list)),
                ("conflict_field", models.CharField(blank=True, max_length=50)),
                ("conflict_new_value", models.CharField(blank=True, max_length=500)),
                ("current_prompt_field", models.CharField(blank=True, max_length=50)),
                (
                    "submitted_inquiry_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of the created properties.Inquiry record.",
                        null=True,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_reason", models.CharField(blank=True, max_length=200)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Session expires 30 minutes after last interaction."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "realbot_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiry_sessions",
                        to="chat.realbotsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inquiry Conversation Session",
                "verbose_name_plural": "Inquiry Conversation Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InquiryConversationAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable log identifier e.g. ICL000001.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("session_started", "Session Started"),
                            ("message_received", "Message Received"),
                            ("field_extracted", "Field Extracted from Message"),
                            ("field_prompted", "Field Prompted"),
                            ("validation_error", "Validation Error"),
                            ("validation_passed", "Validation Passed"),
                            ("field_skipped", "Field Skipped"),
                            ("conflict_detected", "Conflict Detected"),
                            ("conflict_resolved", "Conflict Resolved"),
                            ("confirmation_prompted", "Confirmation Prompted"),
                            ("confirmed", "Customer Confirmed"),
                            ("submitted", "Inquiry Submitted"),
                            ("cancelled", "Session Cancelled"),
                            ("expired", "Session Expired"),
                            ("resumed", "Session Resumed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=50)),
                (
                    "raw_input",
                    models.TextField(
                        blank=True,
                        help_text="Raw user input (PII — masked in admin list view).",
                    ),
                ),
                (
                    "extracted_value",
                    models.TextField(
                        blank=True, help_text="Validated extracted value."
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ics_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="chat.inquiryconversationsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inquiry Audit Log",
                "verbose_name_plural": "Inquiry Audit Logs",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="inquiryconversationsession",
            index=models.Index(fields=["state"], name="chat_inquir_state_554193_idx"),
        ),
        migrations.AddIndex(
            model_name="inquiryconversationsession",
            index=models.Index(
                fields=["realbot_session", "state"],
                name="chat_inquir_realbot_60b3a6_idx",
            ),
        ),
    ]
