# Generated by Django 5.2.6 on 2026-07-07 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0010_m26_inquiry_conversation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessrule",
            name="category",
            field=models.CharField(
                choices=[
                    ("conversation", "Conversation"),
                    ("general", "General"),
                    ("contact", "Contact"),
                    ("property", "Property"),
                    ("nri", "NRI"),
                    ("resources", "Resources"),
                    ("faq", "FAQ"),
                    ("legal", "Legal"),
                    ("financial", "Financial"),
                    ("action", "Action"),
                    ("inquiry", "Inquiry"),
                    ("escalation", "Escalation"),
                    ("fallback", "Fallback"),
                    ("unknown", "Unknown"),
                ],
                default="general",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="inquiryconversationauditlog",
            name="extracted_value",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="inquiryconversationauditlog",
            name="raw_input",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="inquiryconversationsession",
            name="expires_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="inquiryconversationsession",
            name="submitted_inquiry_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SuggestionDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggestion_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable, immutable identifier e.g. SUG000001.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "display_text",
                    models.CharField(
                        help_text="The label text displayed on the suggestion chip.",
                        max_length=150,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Welcome", "Welcome Suggestions"),
                            ("Service", "Service Suggestions"),
                            ("Property", "Property Suggestions"),
                            ("Inquiry", "Inquiry Suggestions"),
                            ("Knowledge", "Knowledge Suggestions"),
                            ("ResourceHub", "Resource Hub Suggestions"),
                            ("GovernmentService", "Government Service Suggestions"),
                            ("Contact", "Contact Suggestions"),
                            ("Navigation", "Navigation Suggestions"),
                            ("Follow-up", "Follow-up Suggestions"),
                            ("Recovery", "Conversation Recovery Suggestions"),
                            ("Completion", "Completion Suggestions"),
                        ],
                        default="Welcome",
                        max_length=50,
                    ),
                ),
                (
                    "parent_context",
                    models.CharField(
                        blank=True,
                        help_text="Associates the suggestion with an intent, service ID or other context.",
                        max_length=100,
                    ),
                ),
                (
                    "trigger_condition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON structure defining matching context e.g. {'intent': 'buy_property'}.",
                    ),
                ),
                (
                    "business_intent",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("greeting", "Greeting"),
                            ("goodbye", "Goodbye"),
                            ("general_information", "General Information"),
                            ("about_propertism", "About Propertism"),
                            ("contact_information", "Contact Information"),
                            ("office_location", "Office Location"),
                            ("business_hours", "Business Hours"),
                            ("buy_property", "Buy Property"),
                            ("sell_property", "Sell Property"),
                            ("rental_income", "Rental Income Management"),
                            ("land_plot", "Land / Plot Services"),
                            ("property_search", "Property Search"),
                            ("property_viewing", "Property Viewing"),
                            ("nri_assist", "NRI Assist"),
                            ("resource_hub", "Resource Hub"),
                            ("useful_links", "Useful Links"),
                            ("faq", "FAQ"),
                            ("terms_conditions", "Terms and Conditions"),
                            ("fee_structure", "Service Fee Structure"),
                            ("patta_chitta", "Patta / Chitta"),
                            ("encumbrance_search", "Encumbrance Search"),
                            ("gcc_property_tax", "GCC Property Tax"),
                            ("whatsapp", "WhatsApp"),
                            ("phone_call", "Phone Call"),
                            ("google_maps", "Google Maps"),
                            ("linkedin", "LinkedIn"),
                            ("inquiry_creation", "Inquiry Creation"),
                            ("human_assistance", "Human Assistance"),
                            ("unknown_intent", "Unknown Intent"),
                        ],
                        help_text="The intent triggered when this suggestion is clicked.",
                        max_length=50,
                    ),
                ),
                (
                    "target_action",
                    models.CharField(
                        blank=True,
                        help_text="Target URL or action description triggered on click.",
                        max_length=250,
                    ),
                ),
                (
                    "display_priority",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Lower values = higher priority. 1=highest, 99=lowest.",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon reference name e.g., 'home', 'phone', 'file-text'.",
                        max_length=50,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Defines display order within the same priority level.",
                    ),
                ),
                (
                    "visibility_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Visibility constraints such as allowed pages list.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Suggestion Definition",
                "verbose_name_plural": "Suggestion Definitions",
                "ordering": ["display_priority", "display_order", "display_text"],
                "indexes": [
                    models.Index(
                        fields=["category", "status"],
                        name="chat_sugges_categor_3b57bd_idx",
                    ),
                    models.Index(
                        fields=["display_priority", "status"],
                        name="chat_sugges_display_aa8c18_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SuggestionInteractionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable log identifier e.g. SGL000001.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "suggestion_id",
                    models.CharField(
                        help_text="The ID of the suggestion definition.", max_length=20
                    ),
                ),
                ("display_text", models.CharField(max_length=150)),
                ("category", models.CharField(max_length=50)),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("rendered", "Rendered to Client"),
                            ("clicked", "Clicked by Client"),
                        ],
                        default="rendered",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggestion_logs",
                        to="chat.realbotsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suggestion Interaction Log",
                "verbose_name_plural": "Suggestion Interaction Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["suggestion_id", "interaction_type"],
                        name="chat_sugges_suggest_4d598d_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="chat_sugges_created_3bfd95_idx"
                    ),
                ],
            },
        ),
    ]
