# Generated by Django 5.2.6 on 2026-07-07 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0011_m27_suggestion_framework"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionDefinition",
            fields=[
                (
                    "action_id",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("action_name", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(max_length=50)),
                ("action_type", models.CharField(max_length=50)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "target_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "target_service",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("supported_parameters", models.JSONField(blank=True, default=list)),
                ("confirmation_required", models.BooleanField(default=False)),
                ("visibility_rules", models.JSONField(blank=True, default=dict)),
                ("security_level", models.CharField(default="public", max_length=20)),
                ("status", models.CharField(default="active", max_length=20)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ActionExecutionLog",
            fields=[
                (
                    "log_id",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("action_id", models.CharField(max_length=20)),
                ("action_name", models.CharField(max_length=100)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("is_validated", models.BooleanField(default=True)),
                ("requires_confirmation", models.BooleanField(default=False)),
                ("is_confirmed", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat.realbotsession",
                    ),
                ),
            ],
        ),
    ]
