# Generated by Django 5.2.6 on 2026-07-07 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0012_actiondefinition_actionexecutionlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponseComponent",
            fields=[
                (
                    "component_id",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("component_type", models.CharField(max_length=50)),
                ("display_template", models.TextField(blank=True, default="")),
                ("content_model", models.JSONField(blank=True, default=dict)),
                ("data_schema", models.JSONField(blank=True, default=list)),
                ("rendering_priority", models.IntegerField(default=10)),
                ("visibility_rules", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(default="active", max_length=20)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResponseCompositionLog",
            fields=[
                (
                    "log_id",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("composition", models.JSONField(blank=True, default=list)),
                ("is_validated", models.BooleanField(default=True)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat.realbotsession",
                    ),
                ),
            ],
        ),
    ]
