# Generated by Django 5.2.6 on 2026-07-07 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0013_responsecomponent_responsecompositionlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationContext",
            fields=[
                (
                    "context_id",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "current_topic",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "previous_topic",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "active_intent",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "active_service",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "active_inquiry_id",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "last_knowledge_topic",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("last_suggested_actions", models.JSONField(blank=True, default=list)),
                ("recent_inputs", models.JSONField(blank=True, default=list)),
                ("pending_questions", models.JSONField(blank=True, default=list)),
                ("outstanding_fields", models.JSONField(blank=True, default=list)),
                ("variables", models.JSONField(blank=True, default=dict)),
                ("conversation_state", models.CharField(default="idle", max_length=50)),
                ("navigation_state", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context",
                        to="chat.realbotsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContextUpdateLog",
            fields=[
                (
                    "log_id",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                (
                    "transition_from",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "transition_to",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("updated_variables", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_logs",
                        to="chat.conversationcontext",
                    ),
                ),
            ],
        ),
    ]
