# Generated by Django 5.2.6 on 2026-07-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0014_conversationcontext_contextupdatelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricAggregate",
            fields=[
                (
                    "aggregate_id",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("metric_key", models.CharField(max_length=100)),
                ("window_type", models.CharField(max_length=20)),
                ("window_start", models.DateTimeField()),
                ("value", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlatformEvent",
            fields=[
                (
                    "event_id",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("session_id", models.CharField(blank=True, max_length=50, null=True)),
                ("provider", models.CharField(max_length=50)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
