# Generated by Django 5.2.6 on 2026-07-07 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0015_metricaggregate_platformevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationItem",
            fields=[
                (
                    "config_id",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(max_length=50)),
                ("config_type", models.CharField(max_length=20)),
                ("value", models.TextField()),
                ("default_value", models.TextField(blank=True, default="")),
                ("validation_rules", models.JSONField(blank=True, default=dict)),
                ("visibility_level", models.CharField(default="admin", max_length=20)),
                ("editable", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=False)),
                ("version", models.IntegerField(default=1)),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "last_modified_by",
                    models.CharField(blank=True, default="admin", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConfigurationAuditLog",
            fields=[
                (
                    "audit_id",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("previous_value", models.TextField(blank=True, default="")),
                ("new_value", models.TextField()),
                ("version", models.IntegerField()),
                ("modified_by", models.CharField(default="admin", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "config_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="chat.configurationitem",
                    ),
                ),
            ],
        ),
    ]
