# Generated by Django 5.2.6 on 2026-07-07 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0016_configurationitem_configurationauditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrchestrationWorkflow",
            fields=[
                (
                    "workflow_id",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("session_id", models.CharField(max_length=50)),
                ("state", models.CharField(default="Initialized", max_length=30)),
                (
                    "current_stage",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowExecutionStep",
            fields=[
                (
                    "step_id",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("stage", models.CharField(max_length=50)),
                ("status", models.CharField(default="success", max_length=20)),
                ("duration_ms", models.IntegerField(default=0)),
                ("logs", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="chat.orchestrationworkflow",
                    ),
                ),
            ],
        ),
    ]
