# Generated by Django 4.2.16 on 2026-07-07 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0018_securityevent_securitypolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeLifecycleAuditLog",
            fields=[
                (
                    "audit_id",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("article_id", models.CharField(blank=True, default="", max_length=20)),
                ("doc_id", models.CharField(blank=True, default="", max_length=20)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("edited", "Edited"),
                            ("archived", "Archived"),
                            ("published", "Published"),
                            ("unpublished", "Unpublished"),
                            ("cloned", "Cloned"),
                            ("versioned", "Versioned"),
                            ("rollback", "Rollback"),
                            ("imported", "Imported"),
                            ("exported", "Exported"),
                            ("reindexed", "Reindexed"),
                            ("validated", "Validated"),
                        ],
                        max_length=30,
                    ),
                ),
                ("performed_by", models.CharField(default="admin", max_length=100)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Knowledge Lifecycle Audit Log",
                "verbose_name_plural": "Knowledge Lifecycle Audit Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="knowledgearticle",
            name="modified_by",
            field=models.CharField(default="admin", max_length=100),
        ),
        migrations.AddField(
            model_name="knowledgearticle",
            name="published_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgearticle",
            name="quality_score",
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name="knowledgearticle",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("review", "Review"),
                    ("approved", "Approved"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                    ("deprecated", "Deprecated"),
                ],
                default="published",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="knowledgearticle",
            name="tags",
            field=models.TextField(
                blank=True, help_text="Comma-separated tags for filtering"
            ),
        ),
        migrations.AddField(
            model_name="knowledgearticle",
            name="usage_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="knowledgearticle",
            name="version",
            field=models.PositiveIntegerField(
                default=1, help_text="Increments on modification"
            ),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="keywords",
            field=models.TextField(
                blank=True, help_text="Space or comma-separated keyword terms"
            ),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="last_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="modified_by",
            field=models.CharField(default="admin", max_length=100),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="published_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="quality_score",
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="search_weight",
            field=models.FloatField(
                default=1.0, help_text="Multiplier applied during relevance scoring"
            ),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("review", "Review"),
                    ("approved", "Approved"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                    ("deprecated", "Deprecated"),
                ],
                default="published",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="usage_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="KnowledgeVersionHistory",
            fields=[
                (
                    "version_id",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField(blank=True)),
                ("main_content", models.TextField(blank=True)),
                ("keywords", models.TextField(blank=True)),
                ("tags", models.TextField(blank=True)),
                ("search_weight", models.FloatField(default=1.0)),
                ("created_by", models.CharField(default="admin", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_history",
                        to="chat.knowledgearticle",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_history",
                        to="chat.knowledgedocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Version History",
                "verbose_name_plural": "Knowledge Version Histories",
                "ordering": ["-version", "-created_at"],
            },
        ),
    ]
