# Generated by Django 5.2.6 on 2026-07-07 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0019_knowledge_admin_framework"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractedKnowledgeCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidate_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable, sequential identifier e.g. KC000001.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_name", models.CharField(max_length=200)),
                ("primary_question", models.CharField(max_length=500)),
                (
                    "alternative_questions",
                    models.TextField(
                        blank=True,
                        help_text="Comma/newline separated or JSON list of alternative questions",
                    ),
                ),
                ("canonical_answer", models.TextField()),
                ("keywords", models.TextField(blank=True)),
                ("synonyms", models.TextField(blank=True)),
                ("source_url", models.CharField(blank=True, max_length=1000)),
                ("source_section", models.CharField(blank=True, max_length=200)),
                ("search_weight", models.FloatField(default=1.0)),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("existing_no_action", "Existing Knowledge (No Action)"),
                            (
                                "existing_update",
                                "Existing Knowledge (Update Recommended)",
                            ),
                            ("new_candidate", "New Knowledge Candidate"),
                            ("duplicate", "Duplicate Candidate"),
                            ("review_required", "Administrator Review Required"),
                        ],
                        default="new_candidate",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "matched_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidates",
                        to="chat.knowledgearticle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extracted Knowledge Candidate",
                "verbose_name_plural": "Extracted Knowledge Candidates",
                "ordering": ["-created_at", "candidate_id"],
            },
        ),
    ]
