# Generated by Django 5.2.6 on 2026-07-09 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0020_extractedknowledgecandidate"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "advisor_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable, immutable advisor identifier e.g. ADV000001.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Advisor display name shown to customers",
                        max_length=200,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Advisor email for notifications", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Optional contact number", max_length=30
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("busy", "Busy"),
                            ("offline", "Offline"),
                        ],
                        default="available",
                        help_text="Current availability status",
                        max_length=20,
                    ),
                ),
                (
                    "max_concurrent_chats",
                    models.PositiveIntegerField(
                        default=3, help_text="Maximum simultaneous conversations"
                    ),
                ),
                (
                    "active_chat_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Current active conversation count"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this advisor is active in the system",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Advisor Profile",
                "verbose_name_plural": "Advisor Profiles",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="HandoverRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "handover_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable, immutable handover identifier e.g. HOV000001.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True, help_text="Customer display name", max_length=200
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True,
                        help_text="Customer email for transcript delivery",
                        max_length=254,
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True, help_text="Customer contact number", max_length=30
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason provided by customer for requesting handover",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about the handover"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_advisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handover_assignments",
                        to="chat.advisorprofile",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="The realBOT session requesting handover",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handover_requests",
                        to="chat.realbotsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Handover Request",
                "verbose_name_plural": "Handover Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HandoverAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable, immutable audit identifier e.g. HAL000001.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("handover_requested", "Handover Requested"),
                            ("handover_accepted", "Handover Accepted"),
                            ("handover_rejected", "Handover Rejected"),
                            ("handover_cancelled", "Handover Cancelled"),
                            ("handover_completed", "Handover Completed"),
                            ("advisor_assigned", "Advisor Assigned"),
                            ("advisor_unavailable", "Advisor Unavailable"),
                            ("message_sent", "Message Sent"),
                            ("transcript_archived", "Transcript Archived"),
                            ("customer_disconnected", "Customer Disconnected"),
                            ("session_closed", "Session Closed"),
                            ("error", "Error Occurred"),
                        ],
                        help_text="The audit action performed",
                        max_length=30,
                    ),
                ),
                (
                    "performed_by",
                    models.CharField(
                        blank=True,
                        help_text="Who performed the action (system, advisor name, customer)",
                        max_length=100,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional details about the audit event",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "handover",
                    models.ForeignKey(
                        help_text="The handover request this audit entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="chat.handoverrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Handover Audit Log",
                "verbose_name_plural": "Handover Audit Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HandoverAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analytics_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable, immutable analytics identifier e.g. HAN000001.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "wait_duration_seconds",
                    models.IntegerField(
                        default=0,
                        help_text="Time customer waited before being assigned to an advisor",
                    ),
                ),
                (
                    "handover_duration_seconds",
                    models.IntegerField(
                        default=0,
                        help_text="Total duration of the handover conversation",
                    ),
                ),
                (
                    "message_count",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of messages exchanged during handover",
                    ),
                ),
                (
                    "customer_satisfaction",
                    models.IntegerField(
                        blank=True,
                        help_text="Customer satisfaction rating (1-5)",
                        null=True,
                    ),
                ),
                (
                    "resolution_status",
                    models.CharField(
                        blank=True,
                        help_text="Whether the handover resolved the customer's issue",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional analytics notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "handover",
                    models.OneToOneField(
                        help_text="The handover request these analytics belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="chat.handoverrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Handover Analytics",
                "verbose_name_plural": "Handover Analytics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archive_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable, immutable archive identifier e.g. ARC000001.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "bot_transcript",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of bot conversation messages before handover",
                    ),
                ),
                (
                    "advisor_transcript",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of advisor conversation messages during handover",
                    ),
                ),
                (
                    "full_transcript",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Combined full transcript of the entire conversation",
                    ),
                ),
                (
                    "conversation_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full conversation structured data",
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("closure_reason", models.CharField(blank=True, max_length=50)),
                ("closed_by", models.CharField(blank=True, max_length=50)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the conversation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        help_text="The realBOT session this archive belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archives",
                        to="chat.realbotsession",
                    ),
                ),
                (
                    "handover",
                    models.OneToOneField(
                        blank=True,
                        help_text="The handover request this archive belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive",
                        to="chat.handoverrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation Archive",
                "verbose_name_plural": "Conversation Archives",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdvisorMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable, immutable message identifier e.g. ADM000001.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[
                            ("advisor", "Advisor"),
                            ("customer", "Customer"),
                            ("system", "System"),
                        ],
                        help_text="Who sent this message",
                        max_length=20,
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name of the sender",
                        max_length=200,
                    ),
                ),
                ("content", models.TextField(help_text="Message content")),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Whether the message has been read"
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "handover",
                    models.ForeignKey(
                        help_text="The handover request this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.handoverrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advisor Message",
                "verbose_name_plural": "Advisor Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TranscriptRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transcript_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable, immutable transcript identifier e.g. TRN000001.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "sender",
                    models.CharField(help_text="Who sent the message", max_length=100),
                ),
                ("message", models.TextField(help_text="The message content")),
                (
                    "message_type",
                    models.CharField(
                        default="text",
                        help_text="Type of message: text, system, handover_notice, etc.",
                        max_length=30,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sequence number for ordering transcript entries",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "archive",
                    models.ForeignKey(
                        help_text="The archive this transcript entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript_entries",
                        to="chat.conversationarchive",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transcript Record",
                "verbose_name_plural": "Transcript Records",
                "ordering": ["sequence", "created_at"],
            },
        ),
    ]
