# Generated by Django 5.2.12 on 2026-03-08 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_contactmessage_fields'),
        ('properties', '0002_property_description_en_property_description_hi_and_more'),
    ]

    operations = [
    ]
