# Generated by Django 5.2.12 on 2026-05-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0004_property_currency"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(fields=["created_at"], name="inquiry_created_idx"),
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(
                fields=["status", "created_at"], name="inquiry_status_created_idx"
            ),
        ),
    ]
