# Generated by Django 5.2.12 on 2026-06-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0008_inquiry_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="assessment_status",
            field=models.CharField(
                blank=True, default="Pending Validation", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="confidence_score",
            field=models.IntegerField(
                blank=True, help_text="Lead Validation Score (0-100)", null=True
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="form_source",
            field=models.CharField(default="Unknown Form", max_length=100),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="spam_score",
            field=models.IntegerField(
                default=0, help_text="Calculated Spam Penalty Points"
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="validation_summary",
            field=models.JSONField(
                blank=True, default=list, help_text="List of rules triggered"
            ),
        ),
    ]
