# Generated by Django 4.2.16 on 2026-07-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "properties",
            "0009_inquiry_assessment_status_inquiry_confidence_score_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="locality",
            field=models.CharField(
                blank=True, help_text="e.g. adyar, velachery", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="nri_status",
            field=models.CharField(
                blank=True, help_text="Yes/No or raw status", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="property_type",
            field=models.CharField(
                blank=True,
                help_text="e.g. apartment, villa, plot, commercial",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="service_needed",
            field=models.CharField(
                blank=True,
                help_text="e.g. buy-sell, rental, industrial",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="user_role",
            field=models.CharField(
                blank=True,
                help_text="e.g. owner, buyer, broker",
                max_length=50,
                null=True,
            ),
        ),
    ]
