# Generated by Django 5.2.6 on 2026-08-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0010_inquiry_locality_inquiry_nri_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="country_code",
            field=models.CharField(
                blank=True,
                help_text="e.g. +91, +48, +971, +1",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="country_name",
            field=models.CharField(
                blank=True,
                help_text="e.g. India, Poland, United Arab Emirates",
                max_length=100,
                null=True,
            ),
        ),
    ]
