# Generated by Django 5.2.12 on 2026-03-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_update_company_contact_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='tagline_en',
            field=models.TextField(default='We manage your property and resources when you are far from the nation.', null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='tagline_hi',
            field=models.TextField(default='We manage your property and resources when you are far from the nation.', null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='tagline_ta',
            field=models.TextField(default='We manage your property and resources when you are far from the nation.', null=True),
        ),
    ]
