# Generated by Codex on 2026-03-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0010_customerreviewsection_homepagecardsection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroBackgroundImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="hero/")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Display order for the hero rotation.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_backgrounds",
                        to="content.companyinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero Background Image",
                "verbose_name_plural": "Hero Background Images",
                "ordering": ["order", "id"],
            },
        ),
    ]
