# Generated by Django 4.2.7 on 2026-02-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary for listing page')),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('author', models.CharField(default='Propertism Team', max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('nri', 'NRI Property Management'), ('market', 'Chennai Real Estate Market'), ('legal', 'Legal & Compliance'), ('maintenance', 'Property Maintenance'), ('investment', 'Investment Strategies'), ('tenant', 'Tenant Management')], default='nri', max_length=20)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Propertism Realty Advisors LLP', max_length=200)),
                ('tagline', models.TextField(default='We manage your property and resources when you are far from the nation')),
                ('about_mission', models.TextField(blank=True)),
                ('about_description', models.TextField(blank=True)),
                ('india_office_address', models.TextField()),
                ('india_office_city', models.CharField(default='Chennai', max_length=100)),
                ('india_office_state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('india_office_pincode', models.CharField(default='600093', max_length=20)),
                ('india_phone_1', models.CharField(max_length=20)),
                ('india_phone_2', models.CharField(blank=True, max_length=20)),
                ('india_phone_3', models.CharField(blank=True, max_length=20)),
                ('us_office_address', models.TextField()),
                ('us_office_city', models.CharField(default='Hackensack', max_length=100)),
                ('us_office_state', models.CharField(default='NJ', max_length=100)),
                ('us_office_zipcode', models.CharField(default='07601', max_length=20)),
                ('us_phone', models.CharField(max_length=20)),
                ('email', models.EmailField(default='info@propertism.com', max_length=254)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/propertism')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com/propertism')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/company/propertism')),
                ('business_hours', models.CharField(default='Monday - Saturday: 9:00 AM - 6:00 PM IST', max_length=200)),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('buy-sell', 'Real Estate Buy & Sell'), ('rental', 'Rental & Maintenance'), ('industrial', 'Industrial Land Services'), ('consultation', 'General Consultation')], max_length=20)),
                ('property_type', models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('plot', 'Plot'), ('commercial', 'Commercial'), ('industrial', 'Industrial Land')], max_length=20)),
                ('message', models.TextField()),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Icon identifier or symbol', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExpertiseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Expertise Area',
                'verbose_name_plural': 'Expertise Areas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-subscribed_date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField(help_text='Brief description for cards')),
                ('full_description', models.TextField(help_text='Detailed description for service page')),
                ('icon', models.CharField(blank=True, help_text='Icon identifier or emoji', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('features', models.TextField(blank=True, help_text='One feature per line')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g., Properties Managed', max_length=100)),
                ('value', models.CharField(help_text='e.g., 500+', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(help_text='e.g., Managing Director', max_length=200)),
                ('department', models.CharField(blank=True, help_text='e.g., Leadership & Strategy', max_length=100)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expertise', models.TextField(blank=True, help_text='Comma-separated expertise areas')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order'],
            },
        ),
    ]
