# Generated by Django 4.2.7 on 2026-02-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_en',
            field=models.TextField(help_text='Short summary for listing page', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_hi',
            field=models.TextField(help_text='Short summary for listing page', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_ta',
            field=models.TextField(help_text='Short summary for listing page', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_description_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_description_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_mission_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_mission_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_mission_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='company_name_en',
            field=models.CharField(default='Propertism Realty Advisors LLP', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='company_name_hi',
            field=models.CharField(default='Propertism Realty Advisors LLP', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='company_name_ta',
            field=models.CharField(default='Propertism Realty Advisors LLP', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tagline_en',
            field=models.TextField(default='We manage your property and resources when you are far from the nation', null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tagline_hi',
            field=models.TextField(default='We manage your property and resources when you are far from the nation', null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tagline_ta',
            field=models.TextField(default='We manage your property and resources when you are far from the nation', null=True),
        ),
        migrations.AddField(
            model_name='corevalue',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='corevalue',
            name='description_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='corevalue',
            name='description_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='corevalue',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='corevalue',
            name='title_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='corevalue',
            name='title_ta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expertisearea',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='expertisearea',
            name='description_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='expertisearea',
            name='description_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='expertisearea',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expertisearea',
            name='title_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expertisearea',
            name='title_ta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description_en',
            field=models.TextField(help_text='Detailed description for service page', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description_hi',
            field=models.TextField(help_text='Detailed description for service page', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description_ta',
            field=models.TextField(help_text='Detailed description for service page', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=models.TextField(help_text='Brief description for cards', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_hi',
            field=models.TextField(help_text='Brief description for cards', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_ta',
            field=models.TextField(help_text='Brief description for cards', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='department_en',
            field=models.CharField(blank=True, help_text='e.g., Leadership & Strategy', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='department_hi',
            field=models.CharField(blank=True, help_text='e.g., Leadership & Strategy', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='department_ta',
            field=models.CharField(blank=True, help_text='e.g., Leadership & Strategy', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_ta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_en',
            field=models.CharField(help_text='e.g., Managing Director', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_hi',
            field=models.CharField(help_text='e.g., Managing Director', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_ta',
            field=models.CharField(help_text='e.g., Managing Director', max_length=200, null=True),
        ),
    ]
