# Generated by Django 4.2.7 on 2026-02-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_blogpost_content_en_blogpost_content_hi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='hero_description',
            field=models.TextField(default='We manage your property and resources when you are far from the nation'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_description_en',
            field=models.TextField(default='We manage your property and resources when you are far from the nation', null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_description_hi',
            field=models.TextField(default='We manage your property and resources when you are far from the nation', null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_description_ta',
            field=models.TextField(default='We manage your property and resources when you are far from the nation', null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_eyebrow',
            field=models.CharField(blank=True, help_text='Small text above hero title', max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_eyebrow_en',
            field=models.CharField(blank=True, help_text='Small text above hero title', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_eyebrow_hi',
            field=models.CharField(blank=True, help_text='Small text above hero title', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_eyebrow_ta',
            field=models.CharField(blank=True, help_text='Small text above hero title', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero background image', null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_title',
            field=models.CharField(default='NRI Property Management Services In India, Chennai', max_length=300),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_title_en',
            field=models.CharField(default='NRI Property Management Services In India, Chennai', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_title_hi',
            field=models.CharField(default='NRI Property Management Services In India, Chennai', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_title_ta',
            field=models.CharField(default='NRI Property Management Services In India, Chennai', max_length=300, null=True),
        ),
    ]
