# Generated by Django 5.2.12 on 2026-03-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_alter_companyinfo_tagline_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="logo",
            field=models.ImageField(blank=True, help_text="Company logo used across the site", null=True, upload_to="company/"),
        ),
    ]
