# Generated by Django 5.2.12 on 2026-03-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_contactinquiry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of name', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(default='info@propertism.in', max_length=254),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://www.facebook.com/PropertismIndia'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='twitter_url',
            field=models.URLField(blank=True, default='https://x.com/PropertismIndia'),
        ),
    ]
