# Generated by Django 5.2.12 on 2026-03-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0008_teammember_slug_alter_companyinfo_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="hero_description_color",
            field=models.CharField(
                default="#475569",
                help_text="Hex color code (e.g., #475569)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="hero_eyebrow_color",
            field=models.CharField(
                default="#B89A4A",
                help_text="Hex color code (e.g., #B89A4A)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="hero_title_color",
            field=models.CharField(
                default="#0F172A",
                help_text="Hex color code (e.g., #0F172A)",
                max_length=7,
            ),
        ),
    ]
