# Generated by Django 5.2.12 on 2026-03-29 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0009_companyinfo_hero_description_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerReviewSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("eyebrow", models.CharField(default="Customer Reviews", max_length=100)),
                ("title", models.CharField(default="What Our Customers Say", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="Hear from customers who trust us for responsive, dependable service.",
                    ),
                ),
                ("badge_title", models.CharField(blank=True, default="Five Star Service", max_length=120)),
                ("badge_text", models.CharField(blank=True, default="Quality Guaranteed", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Customer Review Section",
                "verbose_name_plural": "Customer Review Section",
            },
        ),
        migrations.CreateModel(
            name="HomepageCardSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("eyebrow", models.CharField(blank=True, max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("badge_title", models.CharField(blank=True, max_length=120)),
                ("badge_text", models.CharField(blank=True, max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Homepage Card Section",
                "verbose_name_plural": "Homepage Card Sections",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="HomepageCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("eyebrow", models.CharField(blank=True, max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("footer", models.CharField(blank=True, max_length=160)),
                ("cta_text", models.CharField(blank=True, max_length=80)),
                ("cta_url", models.CharField(blank=True, max_length=300)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="content.homepagecardsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homepage Card",
                "verbose_name_plural": "Homepage Cards",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="CustomerReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("service_label", models.CharField(blank=True, max_length=120)),
                ("customer_name", models.CharField(max_length=120)),
                ("customer_location", models.CharField(blank=True, max_length=120)),
                ("quote", models.TextField()),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                (
                    "avatar_initials",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to generate initials automatically.",
                        max_length=4,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="content.customerreviewsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Review",
                "verbose_name_plural": "Customer Reviews",
                "ordering": ["order"],
            },
        ),
    ]
