# Generated by Django 5.2.12 on 2026-04-21 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0014_landinglead_scoring"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="published_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
