# Generated by Django 5.2.6 on 2026-05-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0015_blogpost_published_date_editable"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="instagram_url",
            field=models.URLField(
                blank=True, default="https://www.instagram.com/propertism"
            ),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="whatsapp_url",
            field=models.URLField(
                blank=True,
                default="https://wa.me/918667020798",
                help_text="WhatsApp link (e.g., https://wa.me/number)",
            ),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="youtube_url",
            field=models.URLField(
                blank=True, default="", help_text="Optional YouTube channel link"
            ),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="blog_section_description",
            field=models.TextField(
                default="Short, practical support for reporting, rentals, maintenance, Chennai"
            ),
        ),
    ]
