# Generated by Django 5.2.12 on 2026-05-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0016_companyinfo_instagram_url_companyinfo_whatsapp_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinfo",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                default="https://www.youtube.com/@propertism",
                help_text="Optional YouTube channel link",
            ),
        ),
    ]
