# Generated by Django 5.2.12 on 2026-06-15 10:46

from django.db import migrations


def update_default_site(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    site, _created = Site.objects.get_or_create(id=1)
    site.domain = "www.propertism.in"
    site.name = "Propertism"
    site.save(update_fields=["domain", "name"])


def reverse_default_site(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    site = Site.objects.get(id=1)
    site.domain = "example.com"
    site.name = "example.com"
    site.save(update_fields=["domain", "name"])


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0017_alter_companyinfo_youtube_url"),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(update_default_site, reverse_default_site),
    ]
