# Generated by Django 5.2.12 on 2026-06-28 15:02

from django.db import migrations


def seed_viji(apps, schema_editor):
    TeamMember = apps.get_model("content", "TeamMember")
    name_val = "Mr. Viji Munuswamy | D.C.T, M.COM."
    role_val = "Technology Consultant & Systems Architect"
    dept_val = "AI Systems & Enterprise Architecture"
    bio_val = "Enterprise Systems Architect leading AI-driven property management workflows, enterprise ERP system architecture, and Propertism's technology integration vision."
    
    TeamMember.objects.update_or_create(
        slug="viji-munuswamy",
        defaults={
            "name": name_val,
            "name_en": name_val,
            "name_ta": name_val,
            "name_hi": name_val,
            "role": role_val,
            "role_en": role_val,
            "role_ta": role_val,
            "role_hi": role_val,
            "department": dept_val,
            "department_en": dept_val,
            "department_ta": dept_val,
            "department_hi": dept_val,
            "bio": bio_val,
            "bio_en": bio_val,
            "bio_ta": bio_val,
            "bio_hi": bio_val,
            "expertise": "Enterprise Architecture, AI Orchestration, ERP Integration, Systems Engineering, Property Technology Vision",
            "order": 99,
            "is_active": True
        }
    )


def unseed_viji(apps, schema_editor):
    TeamMember = apps.get_model("content", "TeamMember")
    TeamMember.objects.filter(slug="viji-munuswamy").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0018_update_default_site_domain"),
    ]

    operations = [
        migrations.RunPython(seed_viji, unseed_viji),
    ]
