# Generated by Django 5.2.12 on 2026-06-28 15:02

from django.db import migrations


def seed_viji(apps, schema_editor):
    TeamMember = apps.get_model("content", "TeamMember")
    TeamMember.objects.update_or_create(
        slug="viji-munuswamy",
        defaults={
            "name": "Mr. Viji Munuswamy | D.C.T, M.COM.",
            "role": "Technology Consultant & Systems Architect",
            "department": "AI Systems & Enterprise Architecture",
            "bio": "Enterprise Systems Architect leading AI-driven property management workflows, enterprise ERP system architecture, and Propertism's technology integration vision.",
            "expertise": "Enterprise Architecture, AI Orchestration, ERP Integration, Systems Engineering, Property Technology Vision",
            "order": 99,
            "is_active": True
        }
    )


def unseed_viji(apps, schema_editor):
    TeamMember = apps.get_model("content", "TeamMember")
    TeamMember.objects.filter(slug="viji-munuswamy").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0018_update_default_site_domain"),
    ]

    operations = [
        migrations.RunPython(seed_viji, unseed_viji),
    ]
