# Generated by Django 5.2.12 on 2026-06-28

from django.db import migrations


def update_viji_bio(apps, schema_editor):
    TeamMember = apps.get_model("content", "TeamMember")
    refined_bio = (
        "Viji Munuswamy is the Technology Consultant & Systems Architect at Propertism. "
        "With over 20 years of technology leadership and 60+ enterprise platform rollouts "
        "across Retail ERP, POS, HCM, FMS, and AI products, he leads the platform architecture, "
        "long-term technical roadmap, and technology integration vision. As Technology Partner, "
        "he specializes in building governed, AI-orchestrated platforms at scale, bridging "
        "the gap between cutting-edge AI systems and robust, enterprise-grade production "
        "environments. He oversees system security, infrastructure stability, and the integration "
        "of automated workflows that empower NRI property owners to manage their Chennai investments "
        "with complete visibility. Driving this AI transformation, he architects next-generation "
        "multi-agent systems, leading the integration of generative AI layers (Gemini, Claude, "
        "and OpenAI) into core operational workflows under strict governance."
    )
    
    TeamMember.objects.filter(slug="viji-munuswamy").update(
        bio=refined_bio,
        bio_en=refined_bio,
        bio_ta=refined_bio,
        bio_hi=refined_bio,
    )


def reverse_viji_bio(apps, schema_editor):
    TeamMember = apps.get_model("content", "TeamMember")
    old_bio = "Enterprise Systems Architect leading AI-driven property management workflows, enterprise ERP system architecture, and Propertism's technology integration vision."
    TeamMember.objects.filter(slug="viji-munuswamy").update(
        bio=old_bio,
        bio_en=old_bio,
        bio_ta=old_bio,
        bio_hi=old_bio,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0020_fix_viji_translation"),
    ]

    operations = [
        migrations.RunPython(update_viji_bio, reverse_viji_bio),
    ]
