# Generated by Django 5.2.6 on 2026-07-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0021_update_viji_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinquiry",
            name="service",
            field=models.CharField(
                blank=True,
                choices=[
                    ("buy-sell", "Sell my Chennai property"),
                    ("rental", "Rent it out and earn income"),
                    ("industrial", "Full property management"),
                    ("consultation", "I need advice first (not sure)"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SpamLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(db_index=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "form_name",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("request_path", models.CharField(blank=True, max_length=200)),
                ("referer", models.CharField(blank=True, max_length=200)),
                (
                    "failure_reason",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("google_error_code", models.CharField(blank=True, max_length=100)),
                ("confidence_score", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Spam Log",
                "verbose_name_plural": "Spam Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "form_name"],
                        name="content_spa_timesta_feff2b_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-timestamp"],
                        name="content_spa_ip_addr_66aabf_idx",
                    ),
                ],
            },
        ),
    ]
