# Generated by Django 4.2.16 on 2026-07-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0022_alter_contactinquiry_service_spamlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinquiry",
            name="service",
            field=models.CharField(
                blank=True,
                choices=[
                    ("buy-sell", "Sell"),
                    ("rental", "Rent"),
                    ("industrial", "Manage"),
                ],
                max_length=20,
            ),
        ),
    ]
